spring.cloud.stream:
  kafka.streams.binder.configuration:
    default.key.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    default.value.serde: org.apache.kafka.common.serialization.Serdes$StringSerde
    commit.interval.ms: 1000
  bindings:
    process-out-0:
      destination: english-counts
    process-out-1:
      destination: french-counts
    process-out-2:
      destination: spanish-counts
    process-in-0:
      destination: words
spring.application.name: kafka-streams-branching-sample
